default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: foodapp
  username: sergiocaminitti
  password: 7532
  host: "localhost"
  port: 5432

test:
  <<: *default
  database: foodapp_test

production:
  <<: *default
  database: foodapp
  username: sergiocaminitti
  password: <%= ENV["AUTH_DATABASE_PASSWORD"] %>
